# fly.toml app configuration file generated for late-resonance-3512 on 2023-07-08T14:20:15+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "late-resonance-3512"
primary_region = "arn"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
